### ISSUE TITLE
Developing on Window using Android Studio cannot open .png

### ISSUE THREAD

**Issue by VovanSuper** [OutSystems/OutSystemsNow-Android#1]
Having installed Android Studio on Windows server 2012R2 trying to develop customised version on OutsysmetsNow-android client app, experiencing set of errors as following (on the attempt of initial make); is it happening due to Windows cannot support so long filenames? :

Error:C:\Users\VladimirO\Desktop\OutSystemsNow-Android-master\outsystems-app-android\Outsytems\platforms\android\build\intermediates\exploded-aar\outsystems-app-android\android-support-v7-appcompat\unspecified\res\drawable-xhdpi-v4\abc_spinner_ab_pressed_holo_light.9.png ERROR: Unable to open PNG file
Execution failed for task ':OutSytems:platforms:android:mergeDebugResources'.

> Error: Failed to run command:
>     C:\Users\VladimirO\AppData\Local\Android\sdk\build-tools\20.0.0\aapt.exe s -i C:\Users\VladimirO\Desktop\OutSystemsNow-Android-master\outsystems-app-android\Outsytems\platforms\android\build\intermediates\exploded-aar\outsystems-app-android\android-support-v7-appcompat\unspecified\res\drawable-hdpi-v4\abc_spinner_ab_disabled_holo_dark.9.png -o C:\Users\VladimirO\Desktop\OutSystemsNow-Android-master\outsystems-app-android\Outsytems\platforms\android\build\intermediates\res\debug\drawable-hdpi-v4\abc_spinner_ab_disabled_holo_dark.9.png
> Error Code:
>     42
> Output:
>     C:\Users\VladimirO\Desktop\OutSystemsNow-Android-master\outsystems-app-android\Outsytems\platforms\android\build\intermediates\exploded-aar\outsystems-app-android\android-support-v7-appcompat\unspecified\res\drawable-hdpi-v4\abc_spinner_ab_disabled_holo_dark.9.png ERROR: Unable to open PNG file

**Comment by marcozero** [comment]
Hi Vovan,

The error is not obvious, but it has to do with the file path length:
"C:\Users\VladimirO\Desktop\OutSystemsNow-Android-master\outsystems-app-android\Outsytems\platforms\android\build\intermediates\exploded-aar\outsystems-app-android\android-support-v7-appcompat\unspecified\res\drawable-xhdpi-v4\abc_spinner_ab_pressed_holo_light.9.png "

If you move your solution out of the desktop to the c:\ for example, it should be solved.

**Comment by developerThami** [comment]
Thank you marcozero
