### ISSUE TITLE
MobileECTController missing?

### ISSUE THREAD

**Issue by ibanezje** [OutSystems/OutSystemsNow-Android#12]
in com.outsystems.android.WebApplicationActivity

import com.outsystems.android.mobileect.MobileECTController;
import com.outsystems.android.mobileect.interfaces.OSECTContainerListener;

are not present.

**Comment by bgracio** [comment]
Hi, everything seems ok with the MobileECTController.

https://github.com/OutSystems/OutSystemsNow-Android/blob/master/outsystems-app-android/Outsystems/platforms/android/src/com/outsystems/android/WebApplicationActivity.java#L69

**Comment by ibanezje** [comment]
Ok, what I meant was the following:
When I load this project in Android Studio, the compiler complains that it cannot find the imports located in package com.outsystems.android.mobileect. ('cannot resolve symbol 'mobileect')
And when you look in package com.outsystems.android there is no 'mobileect' package.

**Comment by bgracio** [comment]
Hi ibanezje,

[Steps for building your own custom app](https://labs.outsystems.net/OutSystemsNowDocs/OutSystemsNowOpenSource.aspx)

Can you please follow this tutorial and see if it helps you. Note that you need to install all the packages listed in the tutorial, but also the most recent Platforms-tools and Build-tools.

**Comment by ibanezje** [comment]
Ok I got it, the MobileECTController was not correctly imported as an dependency.
I added explicitly in Android Studio the MobileECT module as a dependency and it worked.
