### ISSUE TITLE
com.outsystems.android.mobileect.interfaces.OSECTContainerListener cannot be resolved

### ISSUE THREAD

**Issue by ravik3009** [OutSystems/OutSystemsNow-Android#3]
in WebApplicationActivity

**Comment by luissilvaos** [comment]
Hi @ravik3009 ,
Sorry for the late reply. This issue mostly happens when you don't have the correct Android SDK installed and the Android Studio incorrectly imports the project. Which Android SDK versions do you have installed on your computer?

Cheers
