### ISSUE TITLE
Incorrect module/folder name

### ISSUE THREAD

**Issue by mpecenin** [OutSystems/OutSystemsNow-Android#5]
The module name 'OutSytems' is different from the name of the physical folder that's 'Outsytems' (different case). Running Android Studio on Linux, with case sensitive file system, are generated two separate folders during the build and the project "android" is not available to run through the Android Studio.

Doing some find / replace, maintaining the same case used in the folder for the module name, worked properly.

However, I also believe that the 'Outsytems' name is incorrect, lacked a 's'. A few more rename and find / replace could solve that too.

**Comment by luissilvaos** [comment]
Hi @mpecenin,
Thanks for the feedback. The issue is now solved.
Cheers
