### ISSUE TITLE
Inverted image dimensions in the splash screen

### ISSUE THREAD

**Issue by mpecenin** [OutSystems/OutSystemsNow-Android#6]
The following images used in screens with landscape orientation:
... / platforms / android / res / drawable-land-mdpi / bg_red.jpg (320x480)
... / platforms / android / res / drawable-land-xhdpi / bg_red.jpg (640x960)
are with inverted dimensions, it should be:
... land-mdpi / bg_red.jpg (480x320)
... land-xhdpi / bg_red.jpg (960x640)

As the current images are all red, there is no visible problem, but when we customized these images or replaced by others, it is necessary to adjust the dimensions for the images to be displayed correctly in landscape. So, to avoid confusion, it would be interesting to correct the images as they are reference examples.

**Comment by luissilvaos** [comment]
Hi @mpecenin,
Thanks for the feedback. The issue is now solved.
Cheers
